// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
